### ISSUE TITLE
Documentation for beginners

### ISSUE THREAD

**Issue by serge-m** [project-omicron/robocar#1]
As a beginner in ROS,

I want to be able to have a step-by-step instruction list for running simple example with pretrained model.

For example, calibration guide for donkey car: http://docs.donkeycar.com/guide/calibrate/

**Comment by kurbakov** [comment]
Thanks for the ticket, we will work on it, but please take into the account that writing documentation might take some time.

**Comment by serge-m** [comment]
Got it. 
Could you please share a trained model (best_model.h5)?

**Comment by kurbakov** [comment]
The model highly depends on the track and light. So even if we share it, it will be completely useless, because it will not work on the unknown track. What we want to share is the training script. So you can use your data and get the model
